vich_uploader:
    db_driver: orm
    
    mappings:
        imagefood:
            uri_prefix: images_the_district/food
            upload_destination: '%kernel.project_dir%/public/images_the_district/food'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        imagecategorie:
            uri_prefix: images_the_district/category
            upload_destination: '%kernel.project_dir%/public/images_the_district/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
